# Generated by Django 5.2.1 on 2025-05-21 12:01

import delivery_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код промокода', max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Скидка в процентах (0-100)', max_digits=5)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата начала действия')),
                ('valid_to', models.DateTimeField(help_text='Дата окончания действия')),
                ('active', models.BooleanField(default=True, help_text='Активен ли промокод')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[delivery_app.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
