# Generated by Django 5.2.1 on 2025-05-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_promocode_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название точки самовывоза', max_length=100)),
                ('address', models.CharField(help_text='Адрес точки', max_length=200)),
                ('working_hours', models.CharField(help_text="Время работы, например, '10:00-18:00'", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_app.pickuppoint'),
        ),
    ]
