# Generated by Django 5.2.1 on 2025-05-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_order_delivery_method_alter_order_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Адрес доставки для курьера', max_length=200),
        ),
    ]
