# Generated by Django 5.2.1 on 2025-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0012_order_promocode_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение товара', null=True, upload_to='products/'),
        ),
    ]
