# Generated by Django 5.2.1 on 2025-05-31 14:44

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0013_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Изображение товара', null=True, upload_to='products/'),
        ),
    ]
