# Generated by Django 5.2.1 on 2025-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0014_alter_companyinfo_logo_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение товара', null=True, upload_to='products/'),
        ),
    ]
