# Generated by Django 5.2.1 on 2025-05-31 15:24

import delivery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0015_alter_companyinfo_logo_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375 (29) XXX-XX-XX', max_length=20, validators=[delivery_app.models.validate_phone]),
        ),
    ]
