# Generated by Django 5.2.1 on 2025-09-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0020_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_by_years',
            field=models.JSONField(blank=True, default=dict, help_text="История по годам в формате JSON: {'2020': 'Событие', '2021': 'Событие'}"),
        ),
    ]
