# Generated by Django 5.2.1 on 2025-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0021_companyinfo_certificate_companyinfo_history_by_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок раздела')),
                ('content', models.TextField(verbose_name='Содержание раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Раздел политики конфиденциальности',
                'verbose_name_plural': 'Разделы политики конфиденциальности',
                'ordering': ['order'],
            },
        ),
    ]
